<?php

/**
 * @file
 * Custom module for generic tasks.
 */

/**
 * Implements hook_theme_suggestions_HOOK
 */
function rspv_events_theme_suggestions_node(array $variables) {
  $suggestions = [];
  /** @var \Drupal\node\NodeInterface $node */
  $node = $variables['elements']['#node'];
  if($node->bundle() === 'event') {
    if(isset($variables['elements']['#view_mode'])) {
      $suggestions[] = "node__{$variables['elements']['#view_mode']}";
    }
  }
  return $suggestions;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function rspv_events_preprocess_node(&$variables) {
  $node = $variables['elements']['#node'];
  $event_date = $node->get('field_event_date')->getValue()[0]['value'];
  $event_date_day = date('d', strtotime($event_date));
  $event_date_month = date('M', strtotime($event_date));
  $variables['event_date_day'] = $event_date_day;
  $variables['event_date_month'] = $event_date_month;

  // Checking whether the current user is anonymous or not
  $variables['isAnonymous'] = \Drupal::currentUser()->isAnonymous() ? true : false;
  $variables['#attached']['library'][] = 'rspv_events/subscription';
}
